modLoader="javafml"
loaderVersion="[47,)" # поддерживает Forge 47.x
license="MIT"

[[mods]]
modId="heavybullet"
version="0.0.1"
displayName="Heavy Bullet"
authors="Zoritism"
description='''
heavybullet
'''

[[dependencies.heavybullet]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.heavybullet]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
